compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
gpu_ids: 0,1
num_machines: 1
num_processes: 2
machine_rank: 0
mixed_precision: bf16
rdzv_backend: static
main_training_function: main
use_cpu: false
downcast_bf16: 'no'
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
